### ISSUE TITLE
20.04 LTS -> 22.04 LTS in README.md

### ISSUE THREAD

**Issue by isoAdvector** [jakobhaervig/openfoam-dockerfiles#11]

**Comment by jakobhaervig** [comment]
Any reason to upgrade to 22.04 LTS? I had some problems with the repos there and decided not to upgrade yet.

**Comment by isoAdvector** [comment]
I followed the guide, and what was installed was 22.04:

foam@3f281ac0d1fe:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

In the top of the dockerfile it says:
FROM ubuntu:22.04

**Comment by jakobhaervig** [comment]
Thanks, seems like I did verify that 22.04 works. Just forgot to update the README :-) I now updated the README and omitted hardcoding Ubuntu version in there.
