### ISSUE TITLE
Old Docker link in README

### ISSUE THREAD

**Issue by roenby** [jakobhaervig/openfoam-dockerfiles#3]
The link to Docker in step 1 of the README is non-existent and the user is taken to the main docker page.
So the instruction to follow step 4 and 5 does not make sense for the user.

**Comment by jakobhaervig** [comment]
The link should take us to the main Docker Desktop download page:
https://www.docker.com/products/docker-desktop

 Do you suggest direct download links like?
https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe

**Comment by jakobhaervig** [comment]
This has been fixed now.
