### ISSUE TITLE
Which Paraview version to download?

### ISSUE THREAD

**Issue by roenby** [jakobhaervig/openfoam-dockerfiles#4]
In Paraview link in step 1 of the README takes the user to the Paraview download site where one finds many different Paraview versions.
Should the user just take the newest one? Shouldthe use the exe or the zip for Windows? Do they need MPI?

**Comment by jakobhaervig** [comment]
I added more information on this in guide. Some operating systems (macOS) is limited to MPI only but I don't think it matters much for smaller laptops :)
