### ISSUE TITLE
Problem with creating the ESI image

### ISSUE THREAD

**Issue by cheikhnatm** [jakobhaervig/openfoam-dockerfiles#9]
I am facing the following error when I try to create an image with the following command
`docker image build --no-cache -t openfoam $HOME/openfoam-dockerfiles/esi/latest/`

logs : 
`[+] Building 106.8s (10/10) FINISHED                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                           0.0s
 => => transferring dockerfile: 37B                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/ubuntu:focal                                                                                                                1.2s
 => CACHED [1/7] FROM docker.io/library/ubuntu:focal@sha256:4a45212e9518f35983a976eead0de5eecc555a2f047134e9dd2cfc589076a00d                                                   0.0s
 => [2/7] RUN ln -snf /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime && echo Europe/Copenhagen > /etc/timezone                                                           0.2s
 => [3/7] RUN apt-get update && apt-get install -y   ssh   sudo   wget   nano   git   ffmpeg   htop   gnuplot   build-essential   software-properties-common ;  rm -rf /var/  77.0s
 => [4/7] RUN wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash ;    apt-get install -y openfoam-default ;    rm -rf /var/lib/apt/lists/*                   27.4s
 => [5/7] RUN useradd --user-group --create-home --shell /bin/bash foam ; echo "foam ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                                                   0.3s 
 => [6/7] RUN echo "source /usr/lib/openfoam/openfoam/etc/bashrc" >> ~foam/.bashrc ;   echo "export OMPI_MCA_btl_vader_single_copy_mechanism=none" >> ~foam/.bashrc            0.3s 
 => ERROR [7/7] RUN sed -i '/export WM_PROJECT_USER_DIR=/cexport WM_PROJECT_USER_DIR="/data/foam-$WM_PROJECT_VERSION"' /usr/lib/openfoam/openfoam/etc/bashrc                   0.3s 
------                                                                                                                                                                              
 > [7/7] RUN sed -i '/export WM_PROJECT_USER_DIR=/cexport WM_PROJECT_USER_DIR="/data/foam-$WM_PROJECT_VERSION"' /usr/lib/openfoam/openfoam/etc/bashrc:                              
#10 0.310 sed: can't read /usr/lib/openfoam/openfoam/etc/bashrc: No such file or directory
------
executor failed running [/bin/sh -c sed -i '/export WM_PROJECT_USER_DIR=/cexport WM_PROJECT_USER_DIR="/data/foam-$WM_PROJECT_VERSION"' /usr/lib/openfoam/openfoam/etc/bashrc]: exit code: 2`

Where is the error coming from ? I followed every step. 

Thank you for any help

**Comment by jakobhaervig** [comment]
This probably happens if one essential step fails for some reason. I updated the image. Please report if error persists - it should work just fine.
